### ISSUE TITLE
GlyphDrawer Blurry Text

### ISSUE THREAD

**Issue by bforl** [PeterHuberSg/CustomControlBaseLib#1]
Great work Peter, the `GlyphDrawer` is noticeably quicker than `drawingContext.DrawText`

However ...

I have noticed that when I change the scaling on my machine from 100% to 125% (and restart the application) the text is blurry in some places, which only seems to happen when rendering with Glyphs. It's sharp with `drawingContext.DrawText`

Below shows an example of what I mean.

The last row is very sharp.
The first row is a little blurry
The other two rows are very blurry

![image](https://github.com/user-attachments/assets/98c2a5bf-558c-4df6-81c6-ef7d5ed77c06)

To repro

- Set your windows scaling to 125% (be sure to restart the app so WPF picks up the current scaling)
- Use following code as an element of your main window

```
public class TextRenderer : Control
{
    private Typeface _typeface = new Typeface("Verdana");
    private GlyphDrawer? _glyphDrawer;

    public TextRenderer()
    {
        FontFamily = new FontFamily("Verdana");
    }

    protected override void OnRender(DrawingContext drawingContext)
    {
        base.OnRender(drawingContext);

        var ppPerDip = VisualTreeHelper.GetDpi(this).PixelsPerDip;

        for (int i = 0; i < 10; ++i)
        {
            for (int j = 0; j < 10; ++j)
            {
                var text = $"Position {i} {j}";
                var pos = new Point(j * 120, i * 25);

                //RenderText(text, pos, drawingContext, ppPerDip);
                RenderTextGlyph(text, pos, drawingContext, ppPerDip);
            }
        }
    }

    private void RenderTextGlyph(string text, Point pos, DrawingContext drawingContext, double ppPerDip)
    {
        if (_glyphDrawer == null)
            _glyphDrawer = new GlyphDrawer(FontFamily, FontStyle, FontWeight, FontStretch, ppPerDip);

        _glyphDrawer.Write(drawingContext, pos, text, FontSize, Brushes.Black);
    }

    private void RenderText(string text, Point pos, DrawingContext drawingContext, double ppPerDip)
    {
        var formattedText = new FormattedText(text, CultureInfo.CurrentCulture, FlowDirection.LeftToRight, _typeface, FontSize, Brushes.Black, ppPerDip);
        drawingContext.DrawText(formattedText, pos);
    }
}
```

**Comment by bforl** [comment]
Here is another example showing a side by side.

[R] - DrawingContext.RenderText 
[G] - Glyphs

![image](https://github.com/user-attachments/assets/c41eca5b-3ac6-4830-9e6b-3aa38a1698ab)

**Comment by PeterHuberSg** [comment]
Sorry, I don't know why this happens and since it is not a problem for me, I don't have the time to investigate it.

My guess is that the pixel location is off 25% and for that reason what should get painted in one pixel gets painted on 2, one of which with 25%, which makes it look less sharp.

Since it works with drawingContext.DrawText(), you could look into its source code and see what is the difference.
